-- MySQL Script generated by MySQL Workbench
-- Sun Dec 11 18:48:14 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tasks` (
  `idTasks` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idTasks`, `User_idUser`),
  UNIQUE INDEX `idTasks_UNIQUE` (`idTasks` ASC),
  INDEX `fk_Tasks_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Tasks_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Home` (
  `idHome` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `info` LONGTEXT NULL,
  `alarm` TINYINT(1) NOT NULL,
  `Tasks_idTasks` INT NOT NULL,
  UNIQUE INDEX `idHome_UNIQUE` (`idHome` ASC),
  PRIMARY KEY (`idHome`),
  INDEX `fk_Home_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Home_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Work` (
  `idWork` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `info` LONGTEXT NULL,
  `mail` LONGTEXT NULL,
  `coworkers` VARCHAR(45) NULL,
  `alarm` VARCHAR(45) NOT NULL,
  `Tasks_idTasks` INT NOT NULL,
  PRIMARY KEY (`idWork`),
  UNIQUE INDEX `idWork_UNIQUE` (`idWork` ASC),
  INDEX `fk_Work_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Work_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `idPersonal` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `info` LONGTEXT NULL,
  `alarm` VARCHAR(45) NULL,
  `Tasks_idTasks` INT NOT NULL,
  PRIMARY KEY (`idPersonal`),
  UNIQUE INDEX `idPersonal_UNIQUE` (`idPersonal` ASC),
  INDEX `fk_Personal_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Personal_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Travel` (
  `idTravel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date1` DATE NOT NULL,
  `date2` DATE NOT NULL,
  `destination` VARCHAR(45) NOT NULL,
  `pack` LONGTEXT NULL,
  `reminder` LONGTEXT NULL,
  `alarm` VARCHAR(45) NULL,
  `Tasks_idTasks` INT NOT NULL,
  PRIMARY KEY (`idTravel`),
  UNIQUE INDEX `idTravel_UNIQUE` (`idTravel` ASC),
  INDEX `fk_Travel_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Travel_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Shopping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Shopping` (
  `idShopping` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `stuff` LONGTEXT NULL,
  `alarm` TINYINT(1) NULL,
  `Tasks_idTasks` INT NOT NULL,
  PRIMARY KEY (`idShopping`),
  UNIQUE INDEX `idShopping_UNIQUE` (`idShopping` ASC),
  INDEX `fk_Shopping_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Shopping_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Birthday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Birthday` (
  `idBirthday` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `presents` LONGTEXT NULL,
  `alarm` TINYINT(1) NULL,
  `Tasks_idTasks` INT NOT NULL,
  PRIMARY KEY (`idBirthday`),
  UNIQUE INDEX `idBirthday_UNIQUE` (`idBirthday` ASC),
  INDEX `fk_Birthday_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Birthday_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cooking` (
  `idCooking` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `ingredients` LONGTEXT NULL,
  `procedure` LONGTEXT NULL,
  `alarm` TINYINT(1) NULL,
  `Tasks_idTasks` INT NOT NULL,
  PRIMARY KEY (`idCooking`),
  UNIQUE INDEX `idCooking_UNIQUE` (`idCooking` ASC),
  INDEX `fk_Cooking_Tasks1_idx` (`Tasks_idTasks` ASC),
  CONSTRAINT `fk_Cooking_Tasks1`
    FOREIGN KEY (`Tasks_idTasks`)
    REFERENCES `mydb`.`Tasks` (`idTasks`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserTasks` (
  `idUserTasks` INT NOT NULL,
  `idUser` VARCHAR(45) NULL,
  `idTasks` VARCHAR(45) NULL,
  PRIMARY KEY (`idUserTasks`),
  UNIQUE INDEX `idUserTasks_UNIQUE` (`idUserTasks` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
